name: aide_tutorial
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- codecov=2.0.9=py36_0
- coverage=4.4.1=py36_0
- cryptography=1.9=py36_0
- idna=2.5=py36_0
- libffi=3.2.1=3
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.1=py36_0
- pycparser=2.18=py36_0
- pyopenssl=17.2.0=py36_0
- pysocks=1.6.7=py36_0
- python=3.6.0=2
- readline=6.2=0
- requests=2.18.4=py36_1
- setuptools=36.2.2=py36_0
- six=1.10.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- urllib3=1.22=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - aide-design==0.0.2
  - aide-draw==1.0.0
  - aide-tutorial==1.0.0
  - alabaster==0.7.7
  - amqp==1.4.9
  - anyjson==0.3.3
  - appdirs==1.4.3
  - appnope==0.1.0
  - babel==2.3.4
  - beautifulsoup4==4.1.3
  - billiard==3.3.0.23
  - bleach==2.0.0
  - celery==3.1.23
  - celery-haystack==0.10
  - commonmark==0.5.5
  - cssselect==1.0.1
  - cycler==0.10.0
  - decorator==4.1.2
  - defusedxml==0.5.0
  - django==1.9.12
  - django-allauth==0.32.0
  - django-annoying==0.10.1
  - django-appconf==1.0.2
  - django-celery==3.2.1
  - django-copyright==1.0.0
  - django-cors-middleware==1.3.1
  - django-countries==3.4.1
  - django-dynamic-fixture==1.8.5
  - django-extensions==1.7.4
  - django-formtools==1.0
  - django-gravatar2==1.4.0
  - django-guardian==1.4.6
  - django-haystack==2.6.0
  - django-kombu==0.9.4
  - django-messages-extends==0.5
  - django-taggit==0.22.1
  - django-tastypie==0.13.0
  - django-textclassifier==1.0
  - django-vanilla-views==1.0.4
  - djangorestframework==3.5.4
  - djangorestframework-jsonp==1.0.2
  - dnspython==1.15.0
  - docker-py==1.3.1
  - docutils==0.12
  - elasticsearch==1.5.0
  - entrypoints==0.2.3
  - future==0.16.0
  - html5lib==0.999999999
  - httplib2==0.7.7
  - imagesize==0.7.1
  - ipykernel==4.6.1
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2
  - jinja2==2.8
  - jsonfield==1.0.3
  - jsonschema==2.6.0
  - jupyter-client==5.1.0
  - jupyter-contrib-core==0.3.3
  - jupyter-contrib-nbextensions==0.3.1
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.11
  - jupyter-latex-envs==1.3.8.4
  - jupyter-nbextensions-configurator==0.2.7
  - kombu==3.0.37
  - linaro-django-pagination==2.0.2
  - livereload==2.5.1
  - lxml==3.3.5
  - markdown==2.6.9
  - markupsafe==0.23
  - matplotlib==2.0.2
  - mimeparse==0.1.3
  - mistune==0.7.4
  - mkdocs==0.14.0
  - mock==1.0.1
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - nilsimsa==0.3.7
  - notebook==5.0.0
  - numpy==1.13.1
  - oauthlib==2.0.2
  - pandas==0.20.3
  - pandocfilters==1.4.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pint==0.8.1
  - pluggy==0.3.1
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - py==1.4.31
  - pyelasticsearch==0.7.1
  - pygments==2.1.3
  - pyparsing==2.2.0
  - pyquery==1.2.2
  - python-dateutil==2.6.1
  - python-mimeparse==1.6.0
  - python3-openid==3.1.0
  - pytz==2016.4
  - pyyaml==3.12
  - pyzmq==16.0.2
  - readthedocs-build==2.0.6
  - readthedocs-sphinx-ext==0.5.5
  - recommonmark==0.4.0
  - redis==2.10.3
  - requests-oauthlib==0.8.0
  - simplegeneric==0.8.1
  - simplejson==3.11.1
  - slumber==0.7.1
  - snowballstemmer==1.2.1
  - sphinx==1.4.1
  - sphinx-rtd-theme==0.2.4
  - sphinxcontrib-httpdomain==1.4.0
  - sphinxcontrib-websupport==1.0.1
  - stripe==1.20.2
  - terminado==0.6
  - testpath==0.3.1
  - textblob==0.13.0
  - tornado==4.5.2
  - tox==2.3.1
  - tqdm==4.14.0
  - traitlets==4.3.2
  - unipath==1.1
  - virtualenv==15.0.1
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - websocket-client==0.44.0
prefix: /Users/ethankeller/anaconda3/envs/aide_tutorial

